### ISSUE TITLE
Missing spaces/breaks.

### ISSUE THREAD

**Issue by AllTaken** [Sicos1977/IFilterTextReader#12]
Often there are missing spaces/breaks in output from DOCX IFilter.

As in the following example:
Input text:

Mary had a little lamb
that was very pretty.

Result:

"Mary had a little **lambthat** was very pretty. "
Notice the missing space between "lamb" and "that" and the extraneous space after "pretty."

This erroneous result is very common when processing DOCX files.

It happens when two paragraphs are seperated in two chunks at the paragraph break by the IFilter.

I've observed this to (at least usually) be the case when there's a formatting change between the two paragraphs.

You can also see my comment on pull request #11 for further details.

**Comment by AllTaken** [comment]
Closed as "Won't Fix" or?

**Comment by Sicos1977** [comment]
As fixed as it doesn't seem to be a problem anymore in the latest version.

Word:
![capture](https://cloud.githubusercontent.com/assets/6692947/12139539/764b242c-b461-11e5-9a5c-cfd0781e1df9.PNG)

IfilterTextReader:
![capture](https://cloud.githubusercontent.com/assets/6692947/12139525/5b71ab30-b461-11e5-9898-a9f810fc8392.PNG)
