### ISSUE TITLE
Strange Formatting Issue causes break in code

### ISSUE THREAD

**Issue by AdamE87** [Sicos1977/IFilterTextReader#14]
Please see attached file (anonymised) causing issue with IFilter, if you go into the spreadsheet, text appears and is fine...is there an override we could implement?
[Query Detail.zip](https://github.com/Sicos1977/IFilterTextReader/files/184169/Query.Detail.zip)

**Comment by Sicos1977** [comment]
It seems that the file has the wrong extension, did you try to rename the file to .xlsx? Because that is what it is.

**Comment by AdamE87** [comment]
Yeah...I altered my code to just catch the error and re-write the file with a different extension, thanks again
