### ISSUE TITLE
Issue witth FilterLoader.cs

### ISSUE THREAD

**Issue by clorkster** [Sicos1977/IFilterTextReader#15]
I am having an issue with PDFs where the program is hitting the catch inside of "LoadFilterFromDll" inside of FilterLoader.cs.  Specifically, the line that crashes is line 213: 

classFactory.CreateInstance(null, ref filterGuid, out ppunk);

It only happens when the code is moved to the server.  I have the 64-bit adobe Ifilter installed on the server and have confirmed that the 64-bit Ifilter is what is being loaded.

To make the issue even more strange, if I use the same IFilterTextReader.dll for my program and for the viewer that is included in the project, the viewer will succeed.  Both solutions and all projects have identical settings, and the declarations for the FilterReader in the code are identical across solutions.

At this point I am completely stumped and was hoping that perhaps you would have some idea what is happening.  Please let me know if I can clarify anything or provide greater detail.

**Comment by clorkster** [comment]
To add more detail, the generic error that is being thrown is "Error HRESULT E_FAIL has been returned from a call to a COM component"

**Comment by Sicos1977** [comment]
Is the Server windows 2012? And if so did you then use the special job class? need this to make adobe work on a w2k12 server.  See the viewer program about how to use it



Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: clorkster <notifications@github.com> 
Datum: 23-03-2016  21:59  (GMT+01:00) 
Aan: Sicos1977/IFilterTextReader <IFilterTextReader@noreply.github.com> 
Onderwerp: Re: [IFilterTextReader] Issue witth FilterLoader.cs (#15) 

To add more detail, the generic error that is being thrown is "Error HRESULT E_FAIL has been returned from a call to a COM component"

**Comment by clorkster** [comment]
Yes the server is 2012 and that is exactly what the issue was.  Your help is greatly appreciated.

**Comment by Sicos1977** [comment]
Your welcome.  Also a tip,  if speed is a big concern and you have some Money to spend then go for the pdflib i filter because it is much better and faster then the crap that adobe makes


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: clorkster <notifications@github.com> 
Datum: 24-03-2016  16:27  (GMT+01:00) 
Aan: Sicos1977/IFilterTextReader <IFilterTextReader@noreply.github.com> 
Cc: Kees <magic-sessions@home.nl> 
Onderwerp: Re: [IFilterTextReader] Issue witth FilterLoader.cs (#15) 

Yes the server is 2012 and that is exactly what the issue was.  Your help is greatly appreciated.

**Comment by clorkster** [comment]
I actually tried their trial yesterday in the mean time while waiting for a reply and it functioned without the sandbox and was far better as you stated. It has been purchased and implemented. Thanks again!




On Thu, Mar 24, 2016 at 1:41 PM -0700, "Kees" <notifications@github.com> wrote:












    

Your welcome.  Also a tip,  if speed is a big concern and you have some Money to spend then go for the pdflib i filter because it is much better and faster then the crap that adobe makes





Verzonden vanaf mijn Samsung-apparaat



-------- Oorspronkelijk bericht --------

Van: clorkster <notifications@github.com> 

Datum: 24-03-2016  16:27  (GMT+01:00) 

Aan: Sicos1977/IFilterTextReader <IFilterTextReader@noreply.github.com> 

Cc: Kees <magic-sessions@home.nl> 

Onderwerp: Re: [IFilterTextReader] Issue witth FilterLoader.cs (#15) 



Yes the server is 2012 and that is exactly what the issue was.  Your help is greatly appreciated.

**Comment by Sicos1977** [comment]
Just for my own curiosity... for what are you using IFilterTextReader?

**Comment by clorkster** [comment]
A background task to pull full-text information from files for a document management system.
