### ISSUE TITLE
Text extraction hangs when reading .odt file

### ISSUE THREAD

**Issue by andreas-eriksson** [Sicos1977/IFilterTextReader#21]
The extraction of text from an .odt file seems to hang unless the Microsoft Office 2010 Filter Packs is installed.

Is there any reason you can think of why this would happen?

**Comment by Sicos1977** [comment]
No I don't. I just should say that there isn't an IFilter installed for the extension.

**Comment by andreas-eriksson** [comment]
Okay, I will investigate more. Just needs to spin up a new virtual machine and install visual studio.

**Comment by Sicos1977** [comment]
What you also can do is downloading this tool and see if there is another filter coupled to the .odt extension.

http://www.nirsoft.net/utils/search_filter_view.html

**Comment by andreas-eriksson** [comment]
I think I found the error. Have opened a pull request.
