### ISSUE TITLE
Question of requirements:  does not contain a method named 'new'

### ISSUE THREAD

**Issue by ISTTeemuK** [Sicos1977/IFilterTextReader#29]
Hi,

Im trying to use your app with powershell, wich can use your DLL, by next code:
```
$ifpath = "C:\Program Files\PackageManagement\NuGet\Packages\IFilterTextReader.1.6.0\lib\IFilterTextReader.dll"
$asm = [System.Reflection.Assembly]::LoadFrom($ifPath)
$reader = [ifilterTextReader.FilterReader]::new("C:\temp\loremipsum.pdf")
$reader.ReadToEnd()
```
when using ::new method it says does not contain method, this error comes in windows server 2008 R2,
But when on my own windows 10 workstation or windows server 2016, it does work.
So do i need some specific .NET to be installed?

And any help on using for .pdf or older .doc files, as i installed the iFilter plugins for them but still this app wont read them.
.pdf gives error:
Exception calling ".ctor" with "1" argument(s): "DLL name: 'C:\Program Files\Adobe\Adobe PDF iFilter 11 for 64-bit platforms
\bin\PDFFilter.dll'
Class: {E8978DA6-047F-4E3D-9C78-CDBE46041603}'"

Thank you for any assitance you could give me!

**Comment by Sicos1977** [comment]
An adobe i filter needs to be isolated in a job object otherwise I will raise a com exception. This is probably the error you are getting on the server. On Windows 10 you are probably using the default PDF iFilter that is build into Windows 10.

You need this object to make an Adobe PDF iFilter work --> https://github.com/Sicos1977/IFilterTextReader/blob/master/IFilterTextReader/Job.cs

I don't know how to translate this to powershel.

**Comment by ISTTeemuK** [comment]
Ok, il try to figure out how to include job object in my powerhsell script, thanks!

Any idea about the requirements, because even reading .txt files, on windows server 2008 R2, it says new method is missing? I can view the methods with code below, and it doesnt find new method in 2008 R2 server, when viewing methods in 2016 server it lists the new method, like somehow 2008 R2 server is not recognizing new method?
In windows server 2008R2 is .NET 3.5 and .NET 4.5 installed, and in 2016 server only  .NET 4.6 is installed.
```
$ifpath = "C:\temp\tememtest\IFilterTextReader.1.6.0\lib\IFilterTextReader.dll"
$asm = [System.Reflection.Assembly]::LoadFrom($ifPath)
$cbbtypes = $asm.GetExportedTypes()
$cbbtypes | Get-Member -Static|where {$_.typename -eq "IFilterTextReader.FilterReader"}

 TypeName: IFilterTextReader.FilterReader

Name            MemberType Definition                                                           
----            ---------- ----------                                                           
Equals          Method     static bool Equals(System.Object objA, System.Object objB)           
ReferenceEquals Method     static bool ReferenceEquals(System.Object objA, System.Object objB)  
Synchronized    Method     static System.IO.TextReader Synchronized(System.IO.TextReader reader)
Null            Property   static System.IO.TextReader Null {get;}    
```

**Comment by Sicos1977** [comment]
I don't have any idea. Perhaps it has something to do with the Power Shell version that is installed on the server?

**Comment by Sicos1977** [comment]
Good to hear, I'm closing this issue. If you need more help just reopen this issue or make a new one.
