### ISSUE TITLE
TextReader not recognixing line breaks in .docx File

### ISSUE THREAD

**Issue by DHoeschele** [Sicos1977/IFilterTextReader#30]
Hi,
I'm not sure if this is a problem with IFilterTextReader or the Windows IFilter.
I have a docx file with these lines:

FullText Search versus ElasticSearch
Extracting words from MS files and PDFs
Use IFilters to extract text for ElasticSearch 
This is the end

The docx file is attached.
[Test IFilter.docx](https://github.com/Sicos1977/IFilterTextReader/files/2438222/Test.IFilter.docx)

This is returned from FilterReader ReadToEnd()

"FullText" & vbLf & " Search versus ElasticSearchExtractin" & vbLf & "g words from MS files and PDFsUse IFilters to extract text for ElasticSearch This is the end" & vbLf

It seems the vblf's are in the wrong place and ElasticSearchExtracting should be broken into two words.

I'm running Windows 10 and VisualStudio 2017.

Thanks for your help
Dave

**Comment by Sicos1977** [comment]
iFilters are for indexing, there is no options to get the exact same text as how it is in a Word document. A Word document works with formatting like paragraphs, line breaks, etc... and an iFilter doesn't

**Comment by DHoeschele** [comment]
Hi Kees,
Thank you for the reply.  I understand your point. I don’t really care about line breaks, just the words.  But I don’t think Indexing is very useful when it returns

" Search versus ElasticSearchExtractin" & vbLf & "g words

When the input was

FullText Search versus ElasticSearch
Extracting words

Thanks,
Dave

**Comment by Sicos1977** [comment]
It's the iFilter that is returning it that way. iFilterTextReader just returns what a Windows iFilter is returning. I do some cleanup in the code but nothing that gives you  " Search versus ElasticSearchExtractin" & vbLf & "g words

**Comment by DHoeschele** [comment]
OK, Thanks.  I’ll ask MicroSoft about it.  Though I’m not expecting much of an answer from them.
Thanks for your time.  You have developed a nice product.
Dave
