### ISSUE TITLE
Keep file formatting

### ISSUE THREAD

**Issue by traumst** [Sicos1977/IFilterTextReader#31]
Hey,
I want to use your package to analyse content of the files and I need a way to locate the titles in the text.
Is there a way to keep formatting when reading file content?
Stuff like `<b>`, `<u>` or font size definition.

**Comment by Sicos1977** [comment]
As far as I know this is not possible. The IFilterTextReader just returns everything as text because it is normally used to index information so font size, uppercase and so on are not important.
