### ISSUE TITLE
Open File Reader with MemoryStream

### ISSUE THREAD

**Issue by VeredRozen** [Sicos1977/IFilterTextReader#32]
I'm using VS 2017, Windows 10.
I'm trying to read DOCX document from byte array.
When I open a new FiiterReader with a Memory stream (that contains byte array of my document) and the extension "docx", 
it's throws this following exception:
" There is no 64 bits IFilter installed for the stream with the extension 'docx' IFilterTextReader.Exceptions.IFFilterNotFound "

Do you have any idea why I can't read a data from stream?
Thank you,
Vered

**Comment by Sicos1977** [comment]
Did you install the Microsoft Office IFilter pack (64 bits) ?

https://www.microsoft.com/en-us/download/details.aspx?id=17062

**FilterPack64bit.exe**

**Comment by VeredRozen** [comment]
Does it mean that this will also need to be installed on the server?

**Comment by Sicos1977** [comment]
Yes
