### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by JohZant** [Sicos1977/IFilterTextReader#39]
I have recently started using IFilterTextReader to extract the text from all files in a document management system. I have created a windows service to get each document's byte array through a web service and process it.

```
using (Stream stream = new MemoryStream(byteArray))
using (var reader = new FilterReader(stream, extension, filterReaderOptions)) 
{
      text += reader.ReadToEnd();
}
```

I'm having a problem where I get a `System.AccessViolationException` at random times and my Windows Service just terminates.

I thought it was some of the documents at first, but the document that it broke on gets processed when I start the service back up again. 

Here is the Stacktrace.
[AccessViolationException.txt](https://github.com/Sicos1977/IFilterTextReader/files/3748828/AccessViolationException.txt)

Any idea what might be happening here?

**Comment by Sicos1977** [comment]
Are you using the code single or multithreaded?

**Comment by Sicos1977** [comment]
No response ... closed

**Comment by JohZant** [comment]
I was using the code multithreaded, but all the objects that get the document stream and then use the FilterReader were created on the same thread. The only `await` that I had was on the method `ProcessDocuments`.

I spent the last day and a bit taking all the async code out and letting it run. No errors or issues so far. No idea what could have been making it thread unsafe.

**Comment by Sicos1977** [comment]
The code inside IFilterTextReader has parts that are not thread safe. Something I want to fix in the near feature.

**Comment by JohZant** [comment]
Looking at my logs from last night, I have found that there still seems to be some `AccessViolationException`s after my changes. I created a very basic console application this morning to test on, and I have the same thing popping up. The stack trace is a lot smaller this time and I have made sure that it is running single threaded.

```
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at IFilterTextReader.NativeMethods.IFilter.GetValue(IntPtr& pval)
   at IFilterTextReader.FilterReader.Read(Char[] buffer, Int32 index, Int32 count)
   at System.IO.TextReader.ReadToEnd()
   at System.IO.TextReader.SyncTextReader.ReadToEnd()
   at IV.Client.Connectors.IR.GetText(String AuthenticationString, Int32 DocumentID) in IV.Client.Connectors\IR.cs:line 453
   at IV.TestingConsole.Program.Main(String[] args) in IV.TestingConsole\Program.cs:line 69
```

I'm kind of just stabbing in the dark here. I've tried locking the stream and the reader and using `StreamReader.Synchronized`, which has been recommended to others on StackOverflow but I am still getting issues.

**Comment by CBergAccount** [comment]
Was there any solution to this? I am experiencing the same thing. Randomly happens. Seems most often with .doc. but a document working one time does not work Another.

Run in a separate thread but syncronosly.

**Comment by JohZant** [comment]
This is my current solution until it gets fixed. Quite ugly and probably has ramifications that I haven't thought through well enough, but it seems to work for me. There are some parts that are probably not required, like the locks, but as they say, "_If it ain't broke, don't fix it_"
```
public class TextRetrieve
    {
        private readonly byte[] byteArray;

        public TextRetrieve(byte[] byteArray)
        {
            this.byteArray = byteArray;
        }


        [HandleProcessCorruptedStateExceptions]
        public string Retrieve(string extension)
        {
            string result = string.Empty;

            //put the contents into a stream to read
            int count = 0;
            while (count < 10)
            {
                Stream stream = null;
                FilterReader reader = null;
                try
                {
                    stream = new MemoryStream(byteArray);
                    lock (stream)
                    {
                        FilterReaderOptions filterReaderOptions = new FilterReaderOptions();
                        reader = new FilterReader(stream, extension, filterReaderOptions);
                        lock (reader)
                        {
                            string docText = string.Empty;
                            result = reader.ReadToEnd();
                            break;
                        }
                    }
                }
                catch (AccessViolationException)
                {
                    //do nothing, we are trying again
                    count++;
                }
                catch (Exception)
                {
                    throw;
                }
                finally
                {
                    reader?.Dispose();
                    stream?.Dispose();
                }
            }
            return result;
        }
    }
```

Since I never had one specific document that would fail constantly, the class above tries to retrieve the text 10 times on `AccessViolationException`. I have only ever had it get to 3 times tried once. Every other time it gets it on the second go if it fails.

I use this class as follows:
`var text = new TextRetrieve(byteArray).Retrieve(extension);`

Hope this works alright for the time being. If you come up with a better solution, please let me know here.

**Comment by BergChristian** [comment]
Hi, 

Thank you so much for sharing! 

My problem is that the errors takes down my whole application.
HandleProcessCorruptedStateExceptions, does this solve that problem?

**Comment by JohZant** [comment]
Read about it here: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute?view=netframework-4.8

`[HandleProcessCorruptedStateExceptions]` allows you to catch `AccessViolationException` in the method.

**Comment by BergChristian** [comment]
Thank you! I  read in the mean time. I did not know about this, but it saves me a a lot of problems. Gold star and a big thank you!

**Comment by BergChristian** [comment]
and... totally irrelevant, but hey, it is Corona times, a lot of things feels irrelevant. Love Australia. Like my second home from Sweden. Stay safe.

**Comment by JohZant** [comment]
@Sicos1977, has there been an update to fix this issue?

**Comment by Sicos1977** [comment]
I have no idea where to look for this so also no idea how to solve this. I need a good crash report to investigate this.

**Comment by Sicos1977** [comment]
I change the code a little bit, I added some code to free the pointer. So get the latest code from GitHub and see if this solves the problem.

```c#
                        var valuePtr = IntPtr.Zero;

                        try
                        {
                            var valueResult = _filter.GetValue(ref valuePtr);
                        
                            CheckResult(valueResult);

                            switch (valueResult)
                            {
                                case NativeMethods.IFilterReturnCode.FILTER_E_NO_MORE_VALUES:
                                case NativeMethods.IFilterReturnCode.FILTER_E_NO_VALUES:
                                    _chunkValid = false;
                                    break;

                                case NativeMethods.IFilterReturnCode.S_OK:
                                case NativeMethods.IFilterReturnCode.FILTER_S_LAST_VALUES:
                                    var temp = GetPropertyNameAndValue(valuePtr);
                                    if (!string.IsNullOrEmpty(temp))
                                    {
                                        textBuffer = temp.ToCharArray();
                                        textLength = (uint) textBuffer.Length;
                                        textRead = true;
                                    }
    
                                    _chunkValid = false;
                                    break;
                            }
                        }
                        finally
                        {
                            if (valuePtr != IntPtr.Zero)
                                Marshal.Release(valuePtr);
                        }
```

**Comment by Sicos1977** [comment]
I just released IFilterTextReader 1.6.6 to nuget.

**Comment by Sicos1977** [comment]
Please let me know if this makes any differences

**Comment by JohZant** [comment]
I'll do some testing when I get a chance and get back to you. Thank you very much for the update .

**Comment by Sicos1977** [comment]
And?

**Comment by filipnavara** [comment]
If you can produce a memory dump at the time of the crash I'd be happy to look into it. Windows has feature to generate the memory dumps on application crash, it can be enabled in registry. Additionally, we have analyzed 3 AV crashes from our customers in the last 2 days. Two of them have the same underlying cause (https://github.com/Sicos1977/IFilterTextReader/issues/41), the third one is different crash with the same Office filter that was reported to Microsoft (https://aka.ms/AA8lcfh).
