### ISSUE TITLE
Outdated(?) OffFilter.dll on Windows Server 2012

### ISSUE THREAD

**Issue by richardtallent** [Sicos1977/IFilterTextReader#40]
On my Windows Server 2012 box (production), I'm getting a MK_E_INVALIDEXTENSION error when trying to read `.doc` (legacy) files. I confirmed the extension is correct (the files I'm trying to read are linked here, they seem to be valid: https://leg.colorado.gov/agencies/office-legislative-legal-services/2019-crs-titles-download).

Tracing through the server's registry, it is trying to use this DLL, which is dated 3/14/2012 and has a version of 2010.1400.6119.5000:
`C:\Program Files\Common Files\microsoft shared\Filters\OFFFILT.DLL`

On my Windows 10 laptop with Office 2016 installed, the same code runs perfectly, and it is using this DLL, dated 4/11/2018 and with a version of 2008.0.17134.1:
`%systemroot%\system32\OffFilt.dll`

Things I've tried to fix this:

1. Downloading and installing every filter service pack, etc. that I can find and that will let me install it. I believe the server is running Service Pack 2 for 64-bit, but all newer updates to the IFilters are either 404's now or won't install on the server (they claim there's no product installed to update).
2. Editing the server's registry at `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{98de59a0-d175-11cd-a7bd-00006b827d94}\PersistentAddinsRegistered` to use CLSID `{f07f3920-7b8c-11cf-9be8-00aa004b9986}` (the one that points to `%systemroot%\system32\OffFilt.dll` on both machines) instead of `{64F1276A-7A68-4190-882C-5F14B7852019}` (the one pointing to Common Files).
3. Redirecting the path at `{f07f3920-7b8c-11cf-9be8-00aa004b9986}` to a copy of the newer DLL from my laptop. (Couldn't regsvr it either.)
4. Replacing the `Common Files` version of the server's DLL with the laptop's `system32` version.
5. Tried replacing the system32 version, but got trapped in TrustedInstalled permission issues and gave up.

Replacing the DLL or changing the registry path to the newer DLL result in the "There is no 64 bits IFilter..." error.

Do you know of a way to get the IFilter for legacy DOC files updated properly on Windows Server 2012? Or is there a way to force IFilterTextReader to use a specific DLL rather than the ones referenced in the registry? (I know the code doesn't have a manual path override option currently, I can do that part, I'm asking more about whether there's some Dark Magic that requires that IFilter DLLs be registered or something for them to be able to be instantiated by LoadFilterFromDll...)

Thanks for any tips you might be able to provide!

**Comment by Sicos1977** [comment]
Sorry but I now see your issue :-), did you solve your problem?

**Comment by richardtallent** [comment]
Hi! By compiling my code for `Any CPU`, I was able to get it to use the server's old installed 32-bit filters.

Ideally, I would rather have a way to deploy and call the 64-bit DLLs directly. That way I can use the latest DLLs, keep my app in 64-bit mode, and be able to deploy my web app to Azure at some point. But for now, it's working!
