### ISSUE TITLE
OffFilt.dll AccessViolationException

### ISSUE THREAD

**Issue by filipnavara** [Sicos1977/IFilterTextReader#41]
We have started using the library and immediately got a lot of AV errors from our customers. Thankfully we also received the memory dumps and found the underlying issue.

The OffFilt.dll filter for Office files (.doc, .xls, .ppt) has an annoying quirk where it keeps the pointer passed to `IFilter::GetChunk` stored in an internal structure and then later accesses it from `IFilter::GetValue`. The current implementation doesn't pin the memory (or ensure that `STAT_CHUNK` is blittable structure) so it may get moved in memory between the two calls and result in the later `GetValue` code accessing freed memory.

There are multiple ways to resolve the problem but crucially they all involve ensuring that the memory for `FilterReader._chunk` is pinned or allocated on non-movable heap.

**Comment by filipnavara** [comment]
We updated our fork with the following changes and we're now contacting the customers to make sure that they resolve the issue:

```
--- a/Dependencies/IFilterTextReader/IFilterTextReader/NativeMethods.cs
+++ b/Dependencies/IFilterTextReader/IFilterTextReader/NativeMethods.cs
@@ -811,7 +811,7 @@ namespace IFilterTextReader
             /// is the first call to the GetChunk method, and returns a description of the current chunk. 
             /// </summary>
             [PreserveSig]
-            IFilterReturnCode GetChunk(out STAT_CHUNK pStat);
+            IFilterReturnCode GetChunk(IntPtr pStat);
 
             /// <summary>
             /// The IFilter::GetText method retrieves text (text-type properties) from the current chunk, 
--- a/Dependencies/IFilterTextReader/IFilterTextReader/FilterReader.cs
+++ b/Dependencies/IFilterTextReader/IFilterTextReader/FilterReader.cs
@@ -102,6 +102,8 @@ namespace IFilterTextReader
         /// </summary>
         private NativeMethods.STAT_CHUNK _chunk;
 
+        private IntPtr _chunkBuffer;
+
         /// <summary>
         /// Indicates if the <see cref="_chunk"/> is valid
         /// </summary>
@@ -452,9 +454,19 @@ namespace IFilterTextReader
                 // If we don't have a valid chunck anymore then read a new chunck
                 if (!_chunkValid)
                 {
-                    var result = _filter.GetChunk(out _chunk);
+                    if (_chunkBuffer == IntPtr.Zero)
+                    {
+                        _chunkBuffer = Marshal.AllocCoTaskMem(Marshal.SizeOf<NativeMethods.STAT_CHUNK>());
+                    }
+
+                    var result = _filter.GetChunk(_chunkBuffer);
                     _chunkValid = result == NativeMethods.IFilterReturnCode.S_OK;
 
+                    if (_chunkValid)
+                    {
+                        _chunk = Marshal.PtrToStructure<NativeMethods.STAT_CHUNK>(_chunkBuffer);
+                    }
+
                     switch (result)
                     {
                         case NativeMethods.IFilterReturnCode.FILTER_E_PARTIALLY_FILTERED:
@@ -1209,6 +1221,12 @@ namespace IFilterTextReader
             if (_filter != null)
                 Marshal.ReleaseComObject(_filter);
 
+            if (_chunkBuffer != IntPtr.Zero)
+            {
+                Marshal.FreeCoTaskMem(_chunkBuffer);
+                _chunkBuffer = IntPtr.Zero;
+            }
+
             _fileStream?.Dispose();
 
             _stopwatch = null;
```

Additionally, we have an issue opened in Feedback hub for a unrelated AV issue with the same filter (https://aka.ms/AA8lcfh).

**Comment by filipnavara** [comment]
> If this solves the issues then please make a pull request so that I can move the changes into the main trunk

Sure, will do. I just wanted to share our findings first to save time for anyone else hitting the same issue.

**Comment by Sicos1977** [comment]
This is also new for me... pinning something in memory. I try to stay away from pointers since I left C++ land and moved into C# land in 2003. To much problems with pointers :-) ... yes it is fast but also easy to crash a program if you do something wrong.

**Comment by filipnavara** [comment]
I guess the filter was written with the assumption that the application would store `STAT_CHUNK` on the stack and call `IFilter::GetText`/`IFilter::GetValue` right after that thus still having valid memory chunk there. Took me a good day with WinDBG and IDA to figure out what was going on. It could even be worth a blog post at some point but right now I have to focus on shipping our application...

**Comment by Sicos1977** [comment]
Did the changes solve the problem for you customer and if so... do you want to make a pull request so that I can move the changes in the main branch?

**Comment by filipnavara** [comment]
Yes, it did. I'll make a PR. We are just in a release frenzy right now so I didn't get to do it yet.

**Comment by Sicos1977** [comment]
No problems... just was wondering if it got fixed :-)

**Comment by filipnavara** [comment]
Yep, it fixes the issue. We are now improving our monitoring and we spotted few more problematic filters. Notably, XCShInfo.dll from Tracker Software's PDF-xChange seems to either crash or run in endless loop consuming one CPU core. It may happen only on password protected PDF files in this case. I'll share more details in separate issue once we figure out the details. Right now we black-listed the filter and unless we find a better way to deal with it I will submit PR for some kind of black-listing.

**Comment by Sicos1977** [comment]
I just released a new package to nuget ... version 1.7

**Comment by filipnavara** [comment]
Thanks! Regarding the "XCShInfo.dll from Tracker Software's PDF-xChange" issue mentioned above it seems that the `GetChunk` method can return `FILTER_E_PASSWORD` error. This is error is only handled for `GetText`/`GetValue` methods but not in `GetChunk`. It results in an infinite loop. I'll open separate issue / PR to track / fix that.
