### ISSUE TITLE
ReadToEnd() causes "Destination Array Not Long Enough" for legacy Word files

### ISSUE THREAD

**Issue by richardtallent** [Sicos1977/IFilterTextReader#43]
I'm reading legacy (97-2000 BIFF) Word files, and when executing this code, I reliably get the above-mentioned error for an `Array.Copy()` call in `ReadToEnd()`.

```C#
public static string ExtractText(string filePath) {
	using var reader = new FilterReader(filePath, ".doc");
	return reader.ReadToEnd();
}
```

I replaced it with this function, and there are no issues:
```C#
public static string ExtractText(string filePath) {
	using var reader = new FilterReader(filePath, ".doc");
	var sb = new System.Text.StringBuilder();
	var t = reader.ReadLine();
	while (t != null) {
		sb.AppendLine(t);
		t = reader.ReadLine();
	}
	return sb.ToString();
}
```

Both of these files (and many others) exhibit the same issue:
https://www.maine.gov/sos/cec/rules/06/096/096c082.doc
https://www.doa.la.gov/osr/lac/33v07/33v07.doc

Any ideas what's going on? I'm using v1.7.

**Comment by Sicos1977** [comment]
This packages fixes this error --> https://www.nuget.org/packages/IFilterTextReader/1.7.2

What I did is override the default method ReadToEnd() (that was inherrited from TextReader (Microsoft)) with a new method with almost your code in it.
