### ISSUE TITLE
Missing filter return code?

### ISSUE THREAD

**Issue by Spiralis** [Sicos1977/IFilterTextReader#45]
Thanks for maintaining this library. 

I have some old ifilter-code that I am replacing by using your library instead. 

It uses a filter return code that your library does not handle it seems:
```
/// <summary>
/// The docfile has been corrupted
/// </summary>
STG_E_DOCFILECORRUPT = 0x80030109,
```

Is that a possible return type? If so, would it be a candidate to implement?

**Comment by Sicos1977** [comment]
Sure but I never have seen this return code as an IFilter one. I think it is part of reading office files

**Comment by Sicos1977** [comment]
It is also not mentioned as a valid return code for the GetChunk method.

https://docs.microsoft.com/en-us/windows/win32/api/filter/nf-filter-ifilter-getchunk

**Comment by Sicos1977** [comment]
No response, closed

**Comment by Spiralis** [comment]
Thanks for the feedback. 
I am guessing that it was "badly injected" in our code by the original author :)

**Comment by Sicos1977** [comment]
I'm guessing you are the author? ;-)

**Comment by Spiralis** [comment]
Ha-ha. 
I am actually not. Made before my days in the company, and I have no idea who made it. We changed to git about 7 years ago, and the history before then is lost. And the code is really old. I think it is at least 10-15 years old.

And, I'd rather use your library instead of trying to create this myself. Happy to upgrade :)

**Comment by Sicos1977** [comment]
Haha no problems. If you run into something then just make a new issue.
