### ISSUE TITLE
Version 1.7+ - System.ExecutionEngineException and System.AccessViolationException

### ISSUE THREAD

**Issue by JohZant** [Sicos1977/IFilterTextReader#46]
Good evening!

I have been getting some issues with trying to read text using version **1.7** and up of IFilterTextReader. I had the same issues a while ago and raised #39. Towards the end of the issue, there were some changes made and a new version released. I was asked to test these changes but I unfortunately was unable to get around to it.

I had to rewrite some major parts of some software at work in .Net Core so that a problem could be fixed. This took up so much of my time, so I am very sorry that I was not able to provide feedback.

At the start of last week, I started back on where I was up to in May and installed the very latest version of IFilterTextReader (**1.7.3**). 

When using the code that I had used as a work around in https://github.com/Sicos1977/IFilterTextReader/issues/39#issuecomment-600349288 I would get an AV and System.ExecutionEngineException. Both of these errors occur here:
https://github.com/Sicos1977/IFilterTextReader/blob/eb771c85446fda7d055e72bb84f66b7d607930f6/IFilterTextReader/FilterReader.cs#L554

The output to console is shown here: [FatalError.txt](https://github.com/Sicos1977/IFilterTextReader/files/5443099/FatalError.txt).

To see where the second error might have started, I reverted the version each time it came up. The error stopped showing up when I reverted to version **1.6.5** from **1.7**. I am yet to get an AV or a System.ExecutionEngineException on version **1.6.5**.

I am currently using a .NET Core 3.1 Worker Service, which references a .netstandard2.0 library that uses the IFilterTextReader library. This works with version **1.6.5** but not **1.7+**.

I added a .NET Core 3.1 console project to a local git repo with the IFilterTextReader and IFilterTextViewer projects. I implemented the IFilterReader the same way as shown in IFilterTextViewer and got AV exceptions in my .NET Core 3.1 application, however when running your IFilterTextView application, everything works as expected. Could this mean that there is an issue with .Net Core 3.1 in the versions **1.7** and up?

Happy to provide anything that might help!

Thanks,
JohZant

**Comment by gakera** [comment]
We are seeing a `System.AccessViolationException` in `IFilterTextReader Version=1.7.3` after upgrading to .net 5 - but it does not happen on .net 3.1 

I haven't stepped into the library code, but we are just calling `ReadToEnd` and I assume it's similar location: 

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.Release(IntPtr)
   at IFilterTextReader.FilterReader.Read(Char[], Int32, Int32)
   at IFilterTextReader.FilterReader.ReadLine()
   at IFilterTextReader.FilterReader.ReadToEnd()
```

I will try version 1.6.5 of the library, to see if that fixes this.

**Comment by Sicos1977** [comment]
The only change that could explain the memory acces violation is this one I guess..

```c#
                        finally
                        {
                            if (valuePtr != IntPtr.Zero)
                                Marshal.Release(valuePtr);
                        }
```

Could you try the latest version with this removed and see if that solves it?

**Comment by Sicos1977** [comment]
Try version 1.7.4 and see if that fixes it. I just try to catch te exception because I have no idea what is going wrong. I do exactly what needed to be done to free the pointers and memory.

**Comment by gakera** [comment]
I was trying to set up a small test in our regulatory compliance test project, and I have the same problem that is probably what is happening in your new version 1.7.4: `AccessViolationExceptions` can't be caught and handled in the `try / catch` blocks. They are always thrown as unhandled. So for now, the only workaround for me is to use a version which doesn't throw this exception, and we were used to using 1.6.4 so I'll continue using that.

**Comment by Sicos1977** [comment]
Ok learned something new here. Well if you have a document that can reprodure the error it would be helpfull.

**Comment by gakera** [comment]
Attached is just newly created .doc file, which fails when I try `ReadToEnd()`. 

[Sicos1977.zip](https://github.com/Sicos1977/IFilterTextReader/files/5988565/Sicos1977.zip)

Relevant failing code:

```
var fromPath = @"C:\Sicos1977.doc";
var reader = new FilterReader(fromPath, ".doc");
var txt = reader.ReadToEnd();
```

**Comment by Sicos1977** [comment]
Whatever I try I just can't reproduce the error, it just works fine on my system.

**Comment by gakera** [comment]
Visual Studio 2019 on Windows 10 here, not sure if that would make a difference? This also is running in a .net 5 project 
`<TargetFramework>net5.0</TargetFramework>`

**Comment by Sicos1977** [comment]
I tested it on Windows 10 and on Windows 2012 R2 server and on both system everything works fine.

**Comment by JohZant** [comment]
Well, if @gakera is having success on .net 3.1, I am hoping that my issue may possibly be something that I am doing wrong. So, at the risk of outing myself as an idiot, I have added a console app to a fork located [here](https://github.com/JohZant/IFilterTextReader).

Change the `DirectoryPath` at the start of the main method to where ever your documents are located and it will try and read them all. I only put the Sicos1977.doc file from https://github.com/Sicos1977/IFilterTextReader/issues/46#issuecomment-779810841 in my folder and I get the following error:

````
Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.InteropServices.Marshal.Release(IntPtr)
   at IFilterTextReader.FilterReader.Read(Char[], Int32, Int32)
   at IFilterTextReader.FilterReader.ReadLine()
   at IFilterTextReader.FilterReader.ReadToEnd()
   at ConsoleApp1.Program.TryReadFile(System.IO.FileInfo)
   at ConsoleApp1.Program.Main(System.String[])
````

When debugging, the exception message says `Exception of type 'System.ExecutionEngineException' was thrown.`

**Comment by gakera** [comment]
I modified @JohZant's console app to reflect my use, and I have the same results. 
https://github.com/gakera/IFilterTextReader

.net3.1 throws `ExecutionEngineException`, .net 5 throws `AccessViolationException`.

**Comment by RockNHawk** [comment]
> Attached is just newly created .doc file, which fails when I try `ReadToEnd()`.
> 
> [Sicos1977.zip](https://github.com/Sicos1977/IFilterTextReader/files/5988565/Sicos1977.zip)
> 
> Relevant failing code:
> 
> ```
> var fromPath = @"C:\Sicos1977.doc";
> var reader = new FilterReader(fromPath, ".doc");
> var txt = reader.ReadToEnd();
> ```
> 
> tested on `1.7.4` and `AccessViolationException` is thrown.

I have same results. I retargeting the IFilterTextViewer.csproj to net5.0-windows , read your file get the same result.

	<?xml version="1.0" encoding="utf-8"?>
	<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	  <PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net5.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
		<EnableDefaultContentItems>false</EnableDefaultContentItems>
		<EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	  </PropertyGroup>
	  
	<PropertyGroup>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
		<ProjectGuid>{7E0C9F1B-0E41-4653-BE50-187566FB82EC}</ProjectGuid>
		<OutputType>WinExe</OutputType>
		<AppDesignerFolder>Properties</AppDesignerFolder>
		<RootNamespace>IFilterTextViewer</RootNamespace>
		<AssemblyName>IFilterTextViewer</AssemblyName>
		<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
		<FileAlignment>512</FileAlignment>
		<TargetFrameworkProfile />
	  </PropertyGroup>
	  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<PlatformTarget>AnyCPU</PlatformTarget>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	  </PropertyGroup>
	  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<PlatformTarget>AnyCPU</PlatformTarget>
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	  </PropertyGroup>
	  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
		<DebugSymbols>true</DebugSymbols>
		<OutputPath>bin\x86\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<DebugType>full</DebugType>
		<PlatformTarget>x86</PlatformTarget>
		<ErrorReport>prompt</ErrorReport>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	  </PropertyGroup>
	  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
		<OutputPath>bin\x86\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<Optimize>true</Optimize>
		<DebugType>pdbonly</DebugType>
		<PlatformTarget>x86</PlatformTarget>
		<ErrorReport>prompt</ErrorReport>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
	  </PropertyGroup>
	  <PropertyGroup>
		<ApplicationIcon>filter.ico</ApplicationIcon>
	  </PropertyGroup>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	  <ItemGroup>
		<Compile Include="Reader.cs" />
		<Compile Include="MainForm.cs">
		  <SubType>Form</SubType>
		</Compile>
		<Compile Include="MainForm.Designer.cs">
		  <DependentUpon>MainForm.cs</DependentUpon>
		</Compile>
		<Compile Include="Program.cs" />
		<Compile Include="Properties\AssemblyInfo.cs" />
		<EmbeddedResource Include="MainForm.resx">
		  <DependentUpon>MainForm.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Include="Properties\Resources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Resources.Designer.cs</LastGenOutput>
		  <SubType>Designer</SubType>
		</EmbeddedResource>
		<Compile Include="Properties\Resources.Designer.cs">
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Resources.resx</DependentUpon>
		  <DesignTime>True</DesignTime>
		</Compile>
		<None Include="app.config" />
		<None Include="packages.config" />
		<None Include="Properties\Settings.settings">
		  <Generator>SettingsSingleFileGenerator</Generator>
		  <LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		<Compile Include="Properties\Settings.Designer.cs">
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		</Compile>
	  </ItemGroup>
	  <ItemGroup>
		<ProjectReference Include="..\IFilterTextReader\IFilterTextReader.csproj">
		  <Project>{86693e2d-c3cb-4e16-9684-94445934a9d3}</Project>
		  <Name>IFilterTextReader</Name>
		</ProjectReference>
	  </ItemGroup>
	  <ItemGroup>
		<Content Include="filter.ico" />
	  </ItemGroup>
	  <ItemGroup>
		<PackageReference Include="Microsoft.Win32.Registry" Version="6.0.0-preview.1.21102.12" />
		<PackageReference Include="System.Resources.Extensions" Version="6.0.0-preview.1.21102.12" />
		<PackageReference Include="System.Security.AccessControl" Version="6.0.0-preview.1.21102.12" />
		<PackageReference Include="System.Security.Principal.Windows" Version="6.0.0-preview.1.21102.12" />
	  </ItemGroup>
	  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
	  
	</Project>

**Comment by Happi-cat** [comment]
Played a bit with code and my samples and got it working with next change #47
Would be good to review/validate that fix. 

Few notes about AcessViolationException I've got in my app:
* I was getting AcccessViolationException from time to time in .net472 app when tried to process batch of files in the same process. And wasn't getting error when tried to process one file per new process.
* Was getting AccessViolation all the time in .net5 app

**Comment by Sicos1977** [comment]
I just uploaded a new package to nuget

**Comment by JohZant** [comment]
Tested it out and so far, so good.

**Comment by Sicos1977** [comment]
Nice and all credits go to @Happi-cat
