### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by andreas-eriksson** [Sicos1977/IFilterTextReader#50]
The license in the [Readme.md](https://github.com/Sicos1977/IFilterTextReader/blob/master/README.md) (MIT) does not correspond to the license in the [license.txt](https://github.com/Sicos1977/IFilterTextReader/blob/master/license.txt) file (CPOL).

Should any of them be updated?

**Comment by Sicos1977** [comment]
Probably missed that, should be MIT license

**Comment by Sicos1977** [comment]
I deleted the license, in a very past it used to be CPOL because I even didn't know that something like a MIT license existed. But you can do with the iFilterTextReader whatever you want.
