### ISSUE TITLE
IFilterTextReader.Exceptions.IFFilterNotFound: Could not find a 32 bits IFilter dll for a file with an '.docx' extension

### ISSUE THREAD

**Issue by Velocedge** [Sicos1977/IFilterTextReader#55]
I've just installed the latest version of iFilterTextReader using NuGet in VS 2022 and ran into this issue regardless whether it's a doc, docx, xls, xlsx file. I'm running it on a 64 bit laptop so not sure why it's looking for a 32 bit dll.  I have Office 2016 installed and can see 32 filters using SearchFilterViewer.exe which look like they should cover Office files.

 I'm at a bit of a loss where to go next... How can I fix this?

**Comment by Sicos1977** [comment]
If you get the 32 bits message it means it is running in a 32 bits process. The code looks in what kind of process it is running and then gives this exception.

You can find 32 or 64 bits office filters here --> https://www.microsoft.com/en-us/download/details.aspx?id=17062

Did you try the IFilterTextViewer to see what that does --> https://github.com/Sicos1977/IFilterTextReader/tree/master/IFilterTextViewer

**Comment by Velocedge** [comment]
When I try to install the  32 bit iFilter pack, I get an error pop up that says, "Installation of the Microsoft filter pack 2.0 cannot continue.  The MSI installer type does not match the platform architecture."  I will try the IFilterTextViewer but I would assume it would show the same as SearchFilterViewer.exe.  I will let you know.  It is working on my server with the same code.

**Comment by Velocedge** [comment]
This is what I found with the IFilterTextViewer... was definitely different! ;-)  Same content for .xlsx files.

[   at IFilterTextReader.FilterLoader.GetFilterDllAndClass(String extension, String& dllName, String& filterPersistClass) in D:\Data\CADE.Net.Aux\IFilterTextReader-master\IFilterTextReader\FilterLoader.cs:line 407
   at IFilterTextReader.FilterLoader.LoadAndInitIFilter(Stream stream, String extension, Boolean disableEmbeddedContent, String fileName, Boolean readIntoMemory) in D:\Data\CADE.Net.Aux\IFilterTextReader-master\IFilterTextReader\FilterLoader.cs:line 273
   at IFilterTextReader.FilterReader..ctor(String fileName, String extension, FilterReaderOptions filterReaderOptions) in D:\Data\CADE.Net.Aux\IFilterTextReader-master\IFilterTextReader\FilterReader.cs:line 975
   at IFilterTextViewer.MainForm.SelectButton_Click(Object sender, EventArgs e) in D:\Data\CADE.Net.Aux\IFilterTextReader-master\IFilterTextViewer\MainForm.cs:line 121
Could not find a 32 bits IFilter dll for a file with an '.docx' extension
](url)

**Comment by Velocedge** [comment]
Excellent!!  It's working!  I went into Project Properties in VS and on the build tab, "Perfer 32 bit" was checked.  I have no idea why that was checked but I unchecked, compiled, and all is good!  Thanks for the help!
