### ISSUE TITLE
Application frozen on RTF file

### ISSUE THREAD

**Issue by win32nipuh** [Sicos1977/IFilterTextReader#7]
I have installed FilterPack64 and test your utility.
It works fine on .zip files, it is ok.
It does not work on .rtf, it has frozen UI.
It does not work on .pdf - caanot find filter but it installed, SQL Server works fine.

**Comment by Sicos1977** [comment]
It should work on a 64 bit platform, I use the IFilterTextReader on a production platform without any problems. Have you tried to run the code from Visual Studio and tracked done the place where it freezes?

**Comment by win32nipuh** [comment]
I have SQL2012, SQL 2014  installed on my Windows 7 64bit
Also, I have tested other filters it seems they work: txt, doc, pptx...

This query gives me 50 filters, ok
SELECT * FROM sys.fulltext_document_types;

I tried on different rtf files. 
One of them is here 
http://rghost.net/6gJYl6XnW

In all cases exception is here:

if (iPersistStream != null)
            {
                iPersistStream.Load(new IStreamWrapper(stream)); //<--------------!!!
                NativeMethods.IFILTER_FLAGS flags;
                if (iFilter.Init(iflags, 0, IntPtr.Zero, out flags) == NativeMethods.IFilterReturnCode.S_OK)
                    return iFilter;
            }

and exception is:
System.Runtime.InteropServices.COMException (0x8004170C): Exception from HRESULT: 0x8004170C
   at IFilterTextReader.NativeMethods.IPersistStream.Load(IStream pStm)
   at IFilterTextReader.FilterLoader.LoadAndInitIFilter(Stream stream, String extension, Boolean disableEmbeddedContent, String fileName)
   at IFilterTextReader.FilterReader..ctor(Stream stream, String extension, Boolean disableEmbeddedContent, Boolean includeProperties)
   at MindFlavor.RESP.SQLCLR.Redis.fn_GetText(SqlBinary field, SqlString strDocType)

**Comment by win32nipuh** [comment]
There are my filters as sql server shows:

.ascx	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.asm	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.asp	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.aspx	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.bat	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.c	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.cmd	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.cpp	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.cxx	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.def	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.dic	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.doc	C:\Windows\system32\offfilt.dll
.dot	C:\Windows\system32\offfilt.dll
.h	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.hhc	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.hpp	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.htm	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.html	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.htw	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.htx	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.hxx	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.ibq	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.idl	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.inc	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.inf	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.ini	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.inx	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.js	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.log	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.m3u	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.mht	C:\Windows\system32\mimefilt.dll
.obd	C:\Windows\system32\offfilt.dll
.obt	C:\Windows\system32\offfilt.dll
.odc	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.pl	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.pot	C:\Windows\system32\offfilt.dll
.ppt	C:\Windows\system32\offfilt.dll
.rc	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.reg	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.rtf	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.stm	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\nlhtml.dll
.txt	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.url	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.vbs	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.wtx	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\msfte.dll
.xlb	C:\Windows\system32\offfilt.dll
.xlc	C:\Windows\system32\offfilt.dll
.xls	C:\Windows\system32\offfilt.dll
.xlt	C:\Windows\system32\offfilt.dll
.xml	D:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Binn\xmlfilt.dll
